// Generated by CoffeeScript 1.9.3
var isMobilePhone, phoneCorrect, set_scope;

set_scope = function(app_name) {
  return this.ang_scope = angular.element("[ng-app='" + app_name + "']").scope();
};

phoneCorrect = function(element) {
  var not_filled;
  if (!$("#" + element).val()) {
    return false;
  }
  not_filled = $("#" + element).val().match(/_/);
  return not_filled === null;
};

isMobilePhone = function(element) {
  var phone;
  phone = $("#" + element).val();
  if (!phone) {
    return false;
  }
  return !phone.indexOf("+7 (9");
};
