// Generated by CoffeeScript 1.9.3
angular.module("Sms", ["ui.bootstrap"]).controller("Main", function($scope) {
  $scope.pageChanged = function() {
    var redirect_string;
    ajaxStart();
    redirect_string = "sms/" + $scope.currentPage;
    if ($scope.search) {
      redirect_string += "?search=" + $scope.search;
    }
    return redirect(redirect_string);
  };
  return angular.element(document).ready(function() {
    return set_scope("Sms");
  });
});
