	angular.module "Teacher", ["ngMap"]
		.filter 'to_trusted', ['$sce', ($sce) ->
	        return (text) ->
	            return $sce.trustAsHtml(text)
		]
		.filter 'range', () ->
			return (input, total) ->
				total = parseInt total
				for i in [0...total] by 1
					input.push i
				input
		.controller "EditCtrl", ($scope) ->
			$scope.weekdays = [
				{"short" : "ПН", "full" : "Понедельник", 	"schedule": ["", "", "16:15", "18:40"]},
				{"short" : "ВТ", "full" : "Вторник", 		"schedule": ["", "", "16:15", "18:40"]},
				{"short" : "СР", "full" : "Среда", 			"schedule": ["", "", "16:15", "18:40"]},
				{"short" : "ЧТ", "full" : "Четверг", 		"schedule": ["", "", "16:15", "18:40"]},
				{"short" : "ПТ", "full" : "Пятница", 		"schedule": ["", "", "16:15", "18:40"]},
				{"short" : "СБ", "full" : "Суббота", 		"schedule": ["11:00", "13:30", "16:00", "18:30"]},
				{"short" : "ВС", "full" : "Воскресенье",	"schedule": ["11:00", "13:30", "16:00", "18:30"]}
			]
			
			
			initFreetime = (id_branch, day) ->
			  $scope.freetime = initIfNotSet($scope.freetime)
			  $scope.freetime[id_branch] = initIfNotSet($scope.freetime[id_branch])
			  $scope.freetime[id_branch][day] = initIfNotSet($scope.freetime[id_branch][day])
			  return
			
			$scope.inFreetime = (id_branch, day, value) ->
			  initFreetime id_branch, day
			  $.inArray(value, objectToArray($scope.freetime[id_branch][day])) >= 0
			
			$scope.inFreetime2 = (time, freetime) ->
			  freetime = objectToArray(freetime)
			  $.inArray(time, freetime) >= 0
			
			$scope.freetimeClick = (id_branch, index, n) ->
			  index++
			  if $scope.freetime[id_branch][index][n] != true
			    $scope.freetime[id_branch][index][n] = ''
			  else
			    $scope.freetime[id_branch][index][n] = $scope.weekdays[index - 1].schedule[n]
			  return
			
			$scope.selectAllWorking = (id_branch) ->
			  $.each $scope.weekdays, (index, weekday) ->
			    if index > 4
			      return
			    if $scope.freetime_selected_all_working
			      $scope.freetime[id_branch][index + 1][2] = ''
			      $scope.freetime[id_branch][index + 1][3] = ''
			    else
			      $scope.freetime[id_branch][index + 1][2] = weekday.schedule[2]
			      $scope.freetime[id_branch][index + 1][3] = weekday.schedule[3]
			    return
			  $scope.freetime_selected_all_working = !$scope.freetime_selected_all_working
			  return
			
			$scope.selectAllWeek = (id_branch) ->
			  $.each $scope.weekdays, (index, weekday) ->
			    if $scope.freetime_selected_all_week
			      $scope.freetime[id_branch][index + 1][0] = ''
			      $scope.freetime[id_branch][index + 1][1] = ''
			      $scope.freetime[id_branch][index + 1][2] = ''
			      $scope.freetime[id_branch][index + 1][3] = ''
			    else
			      $scope.freetime[id_branch][index + 1][0] = weekday.schedule[0]
			      $scope.freetime[id_branch][index + 1][1] = weekday.schedule[1]
			      $scope.freetime[id_branch][index + 1][2] = weekday.schedule[2]
			      $scope.freetime[id_branch][index + 1][3] = weekday.schedule[3]
			    return
			  $scope.freetime_selected_all_week = !$scope.freetime_selected_all_week
			  return
			
			$scope.selectAllIndex = (id_branch, index) ->
			  $scope.freetime_selected_all_index = initIfNotSet($scope.freetime_selected_all_index)
			  $.each $scope.weekdays, (i, weekday) ->
			    if $scope.freetime_selected_all_index[index]
			      $scope.freetime[id_branch][i + 1][index] = ''
			    else
			      $scope.freetime[id_branch][i + 1][index] = weekday.schedule[index]
			    return
			  $scope.freetime_selected_all_index[index] = !$scope.freetime_selected_all_index[index]
			  return
			
			$scope.saveFreetime = ->
			  lightBoxHide()
			  $('.save-button').click()
			  return
			
			# ---
			# generated by js2coffee 2.1.0
			

			$scope.phoneCorrect = phoneCorrect
			$scope.isMobilePhone = isMobilePhone
			
			angular.element(document).ready ->
				set_scope "Teacher"
				$.each $scope.Teacher.branches, (index, branch) ->
					$scope.Teacher.branches[index] = branch.toString()
			
			$scope.goToTutor = ->
				window.open "https://crm.a-perspektiva.ru/repetitors/edit/?id=#{$scope.Teacher.id_a_pers}", "_blank"
			
			$(document).ready ->
				$("#subjects-select").selectpicker
					noneSelectedText: "предметы"
					multipleSeparator: ", "
				
				$("#teacher-branches").selectpicker
					noneSelectedText: "удобные филиалы для преподавателя"
				
				$("#teacher-edit").on 'keyup change', 'input, select, textarea', ->
					$scope.form_changed = true
					$scope.$apply()
			
			$(".save-button").on "click", ->
					has_errors = false
					
					$(".phone-masked").filter ->
						not_filled = $(this).val().match(/_/)
						
						if not_filled isnt null
							$(this).addClass("has-error").focus()
							notifyError("Номер телефона указан неполностью")
							has_errors = true
							return false
						else
							$(this).removeClass("has-error")
						
					if has_errors
						return false
					
					$scope.Teacher.subjects = []
					$("#subjects-select option:selected").each ->
						if $(@).val()
							$scope.Teacher.subjects.push $(@).val()
					
					$scope.Teacher.branches = []
					$("#teacher-branches option:selected").each ->
						if $(@).val()
							$scope.Teacher.branches.push $(@).val()
					
					ajaxStart()
					$scope.saving = true
					$scope.$apply()
					
					$scope.Teacher.freetime = $scope.freetime
					$.post "teachers/ajax/save", $scope.Teacher, (response) ->
						console.log response
						if $scope.Teacher.id
							ajaxEnd()
							$scope.saving = false
							$scope.form_changed = false
							$scope.$apply()
						else
							redirect "teachers/edit/#{response}"	
						
		.controller "ListCtrl", ($scope) ->
			$scope.deleteTeacher = (id_teacher, index) ->
				bootbox.confirm "Вы уверены, что хотите удалить преподавателя №#{id_teacher}?", (result) ->
					if result is true
						$scope.Teachers.splice index, 1
						$scope.$apply()
						$.post "teachers/ajax/delete", {id_teacher: id_teacher}
						console.log "here", index, id_teacher