CREATE TABLE `last_call_data` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` CHAR(11) NOT NULL COMMENT 'номер',
	`user_id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'login сотрудника',
	`time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'время звонка',
	PRIMARY KEY (`id`),
	UNIQUE INDEX (`phone`)
)
ENGINE=InnoDB
AUTO_INCREMENT=5;
